### ISSUE TITLE
Feature Request: Work with novert.com?

### ISSUE THREAD

**Issue by Sowden** [Sakitoshi/mbf_sigil#2]
Hey there.  I just discovered this and I'm able to play Sigil 2 on my retro laptop, which is amazing.  I do have one request though, could you make it compatible with novert.com?  Its a small program that disables the forward and backward motion on moving your mouse forward.  That would make everything work with WASD on my retro laptop.  You can get the mod below, its really simple to apply it.  Just run it before running MBF.EXE.  Do you think it could be done?  Thanks for the great work.

https://www.doomworld.com/idgames/utils/misc/novert

**Comment by Sakitoshi** [comment]
mbf already has separate horizontal and vertical mouse sensitivity.

**Comment by Sowden** [comment]
I had no idea this feature was already available!  Afte doing some deep searching I figured it out.  In case anyone finds this and wants to know how, in the main Doom menu, go to Options -> Mouse Sensitivity and take the "Vertical" bar all the way to the left.  Your mouse will no longer move you forward.  Thanks for the great software!
